window.STORIES = [
  {
    "id": "st1",
    "title": "Un café",
    "emoji": "☕",
    "unit": "u3",
    "xp": 22,
    "lines": [
      {"type": "narr", "es": "Lucía está en un café pequeño.", "en": "Lucía is in a small café."},
      {"type": "say", "speaker": "Lucía", "avatar": "👩", "es": "¡Buenos días! Un café con leche, por favor.", "en": "Good morning! A coffee with milk, please."},
      {"type": "say", "speaker": "Mario", "avatar": "👨‍🍳", "es": "¡Claro! ¿Algo más?", "en": "Of course! Anything else?"},
      {"type": "say", "speaker": "Lucía", "avatar": "👩", "es": "Sí, un pan dulce, por favor.", "en": "Yes, a sweet pastry, please."},
      {"type": "q", "prompt": "What does Lucía order?", "choices": ["A coffee with milk and a pastry", "A tea and a soup", "Only water"], "answer": 0},
      {"type": "narr", "es": "Mario llega con un té y una sopa.", "en": "Mario arrives with a tea and a soup."},
      {"type": "say", "speaker": "Lucía", "avatar": "👩", "es": "Perdón, esto es un té. Yo quiero un café.", "en": "Excuse me, this is a tea. I want a coffee."},
      {"type": "say", "speaker": "Mario", "avatar": "👨‍🍳", "es": "¡Ay, no! Lo siento mucho. Hoy es mi primer día.", "en": "Oh no! I am so sorry. Today is my first day."},
      {"type": "q", "prompt": "What does Mario bring by mistake?", "choices": ["A coffee and a pastry", "A tea and a soup", "Two coffees"], "answer": 1},
      {"type": "say", "speaker": "Lucía", "avatar": "👩", "es": "Está bien. ¡Me gusta la sopa!", "en": "It's okay. I like soup!"},
      {"type": "narr", "es": "Mario regresa con el café y el pan dulce.", "en": "Mario comes back with the coffee and the pastry."},
      {"type": "say", "speaker": "Mario", "avatar": "👨‍🍳", "es": "El café es gratis hoy, señorita.", "en": "The coffee is free today, miss."},
      {"type": "q", "prompt": "Why is the coffee free?", "choices": ["It is Lucía's birthday", "Lucía has no money", "Mario made a mistake"], "answer": 2},
      {"type": "say", "speaker": "Lucía", "avatar": "👩", "es": "¡Gracias! Este café es mi favorito.", "en": "Thank you! This café is my favorite."},
      {"type": "say", "speaker": "Mario", "avatar": "👨‍🍳", "es": "¿La sopa también?", "en": "The soup too?"},
      {"type": "narr", "es": "Lucía ríe y come la sopa con su café.", "en": "Lucía laughs and eats the soup with her coffee."}
    ]
  },
  {
    "id": "st2",
    "title": "El cumpleaños",
    "emoji": "🎂",
    "unit": "u5",
    "xp": 23,
    "lines": [
      {"type": "narr", "es": "Hoy es el cumpleaños del abuelo de Ana.", "en": "Today is Ana's grandfather's birthday."},
      {"type": "say", "speaker": "Ana", "avatar": "👧", "es": "¡Feliz cumpleaños, abuelo!", "en": "Happy birthday, Grandpa!"},
      {"type": "say", "speaker": "Abuelo", "avatar": "👴", "es": "¡Gracias, Ana! Hoy cumplo setenta años.", "en": "Thank you, Ana! I turn seventy today."},
      {"type": "q", "prompt": "How old is Grandpa today?", "choices": ["Sixty", "Seventy", "Seventeen"], "answer": 1},
      {"type": "say", "speaker": "Ana", "avatar": "👧", "es": "¡Setenta! ¿Cuántas velas hay en el pastel?", "en": "Seventy! How many candles are on the cake?"},
      {"type": "say", "speaker": "Abuelo", "avatar": "👴", "es": "Solo siete. Una vela por cada diez años.", "en": "Only seven. One candle for every ten years."},
      {"type": "narr", "es": "La familia canta y el abuelo sonríe.", "en": "The family sings and Grandpa smiles."},
      {"type": "q", "prompt": "How many candles are on the cake?", "choices": ["Seventy", "Ten", "Seven"], "answer": 2},
      {"type": "say", "speaker": "Ana", "avatar": "👧", "es": "Abuelo, ¿cuál es tu regalo favorito?", "en": "Grandpa, what is your favorite present?"},
      {"type": "say", "speaker": "Abuelo", "avatar": "👴", "es": "Tu visita, Ana. La familia es el mejor regalo.", "en": "Your visit, Ana. Family is the best present."},
      {"type": "narr", "es": "Ana le da un dibujo de los dos.", "en": "Ana gives him a drawing of the two of them."},
      {"type": "say", "speaker": "Abuelo", "avatar": "👴", "es": "¡Me encanta! Gracias, mi niña.", "en": "I love it! Thank you, my dear."},
      {"type": "q", "prompt": "What does Ana give her grandfather?", "choices": ["A drawing", "A cake", "A candle"], "answer": 0},
      {"type": "say", "speaker": "Ana", "avatar": "👧", "es": "El próximo año quiero ver ocho velas.", "en": "Next year I want to see eight candles."},
      {"type": "narr", "es": "Todos comen pastel y ríen juntos.", "en": "Everyone eats cake and laughs together."}
    ]
  },
  {
    "id": "st3",
    "title": "El tren a Madrid",
    "emoji": "🚆",
    "unit": "u7",
    "xp": 24,
    "lines": [
      {"type": "narr", "es": "Marco está en la estación de tren.", "en": "Marco is at the train station."},
      {"type": "say", "speaker": "Marco", "avatar": "👨", "es": "Perdón, ¿dónde está el tren a Madrid?", "en": "Excuse me, where is the train to Madrid?"},
      {"type": "say", "speaker": "Agente", "avatar": "👮‍♀️", "es": "El tren a Madrid sale del andén cinco.", "en": "The train to Madrid leaves from platform five."},
      {"type": "q", "prompt": "Which platform does the Madrid train leave from?", "choices": ["Platform nine", "Platform five", "Platform two"], "answer": 1},
      {"type": "say", "speaker": "Marco", "avatar": "👨", "es": "¿A qué hora sale el tren?", "en": "What time does the train leave?"},
      {"type": "say", "speaker": "Agente", "avatar": "👮‍♀️", "es": "Sale a las tres y media.", "en": "It leaves at three thirty."},
      {"type": "narr", "es": "Son las tres y veinte. ¡Marco tiene diez minutos!", "en": "It is three twenty. Marco has ten minutes!"},
      {"type": "q", "prompt": "How much time does Marco have?", "choices": ["Thirty minutes", "Two minutes", "Ten minutes"], "answer": 2},
      {"type": "narr", "es": "Marco corre con su maleta grande.", "en": "Marco runs with his big suitcase."},
      {"type": "say", "speaker": "Marco", "avatar": "👨", "es": "¡Andén cinco! ¿Dónde está el andén cinco?", "en": "Platform five! Where is platform five?"},
      {"type": "say", "speaker": "Agente", "avatar": "👮‍♀️", "es": "¡Señor, está aquí! Usted está en el andén cinco.", "en": "Sir, it's here! You are on platform five."},
      {"type": "say", "speaker": "Marco", "avatar": "👨", "es": "¿Aquí? ¡Qué suerte!", "en": "Here? What luck!"},
      {"type": "q", "prompt": "Where is Marco standing?", "choices": ["On platform five", "On platform nine", "In the café"], "answer": 0},
      {"type": "narr", "es": "Marco sube al tren a las tres y veintinueve.", "en": "Marco gets on the train at three twenty-nine."},
      {"type": "say", "speaker": "Marco", "avatar": "👨", "es": "Madrid, ¡aquí voy!", "en": "Madrid, here I come!"},
      {"type": "narr", "es": "La agente sonríe. Cada día hay un Marco.", "en": "The agent smiles. Every day there is a Marco."}
    ]
  },
  {
    "id": "st4",
    "title": "Un día de lluvia",
    "emoji": "🌧️",
    "unit": "u10",
    "xp": 21,
    "lines": [
      {"type": "narr", "es": "Llueve mucho hoy. Sara y Leo están en casa.", "en": "It is raining a lot today. Sara and Leo are at home."},
      {"type": "say", "speaker": "Leo", "avatar": "👦", "es": "Mamá, quiero jugar en el parque.", "en": "Mom, I want to play in the park."},
      {"type": "say", "speaker": "Sara", "avatar": "👩‍🦰", "es": "No, Leo. Hoy llueve y hace frío.", "en": "No, Leo. Today it's raining and it's cold."},
      {"type": "q", "prompt": "Why can't Leo go to the park?", "choices": ["It is raining and cold", "It is too hot", "The park is closed"], "answer": 0},
      {"type": "say", "speaker": "Leo", "avatar": "👦", "es": "¿Y si llevo mi paraguas?", "en": "And what if I take my umbrella?"},
      {"type": "say", "speaker": "Sara", "avatar": "👩‍🦰", "es": "Tu paraguas es muy pequeño, Leo.", "en": "Your umbrella is very small, Leo."},
      {"type": "say", "speaker": "Sara", "avatar": "👩‍🦰", "es": "¿Hacemos una casa de mantas en la sala?", "en": "Should we make a blanket house in the living room?"},
      {"type": "say", "speaker": "Leo", "avatar": "👦", "es": "¡Sí! ¡Una casa grande!", "en": "Yes! A big house!"},
      {"type": "q", "prompt": "What do Sara and Leo decide to make?", "choices": ["Cookies", "A blanket house", "A boat"], "answer": 1},
      {"type": "narr", "es": "Hacen la casa con mantas y sillas.", "en": "They make the house with blankets and chairs."},
      {"type": "say", "speaker": "Leo", "avatar": "👦", "es": "Mamá, ¡mira! ¡El sol!", "en": "Mom, look! The sun!"},
      {"type": "narr", "es": "La lluvia termina y sale el sol.", "en": "The rain ends and the sun comes out."},
      {"type": "say", "speaker": "Sara", "avatar": "👩‍🦰", "es": "¿Quieres ir al parque ahora?", "en": "Do you want to go to the park now?"},
      {"type": "say", "speaker": "Leo", "avatar": "👦", "es": "No, mamá. ¡Me gusta más nuestra casa!", "en": "No, Mom. I like our house better!"},
      {"type": "q", "prompt": "What does Leo want to do at the end?", "choices": ["Go to the park", "Watch TV", "Stay in the blanket house"], "answer": 2},
      {"type": "narr", "es": "Sara y Leo beben chocolate caliente en su casa nueva.", "en": "Sara and Leo drink hot chocolate in their new house."}
    ]
  },
  {
    "id": "st5",
    "title": "El partido de fútbol",
    "emoji": "⚽",
    "unit": "u13",
    "xp": 25,
    "lines": [
      {"type": "narr", "es": "Diego y Carmen están en el estadio.", "en": "Diego and Carmen are at the stadium."},
      {"type": "say", "speaker": "Diego", "avatar": "👨", "es": "¡Hoy juega mi equipo favorito, los Tigres!", "en": "My favorite team, the Tigres, plays today!"},
      {"type": "say", "speaker": "Carmen", "avatar": "👩", "es": "Yo soy fan de los Leones.", "en": "I am a Leones fan."},
      {"type": "q", "prompt": "Which team does Carmen support?", "choices": ["The Tigres", "The Leones", "Neither team"], "answer": 1},
      {"type": "narr", "es": "El partido empieza. Los jugadores corren rápido.", "en": "The game starts. The players run fast."},
      {"type": "say", "speaker": "Diego", "avatar": "👨", "es": "¡Mira! ¡Gol de los Tigres!", "en": "Look! A goal for the Tigres!"},
      {"type": "say", "speaker": "Carmen", "avatar": "👩", "es": "Tranquilo, Diego. El partido es largo.", "en": "Calm down, Diego. The game is long."},
      {"type": "narr", "es": "Los Leones juegan bien y hacen dos goles.", "en": "The Leones play well and score two goals."},
      {"type": "q", "prompt": "What is the score now?", "choices": ["Tigres 1, Leones 2", "Tigres 2, Leones 1", "Tigres 0, Leones 0"], "answer": 0},
      {"type": "say", "speaker": "Carmen", "avatar": "👩", "es": "¡Dos a uno! ¡Vamos, Leones!", "en": "Two to one! Let's go, Leones!"},
      {"type": "narr", "es": "En el último minuto, los Tigres hacen otro gol.", "en": "In the last minute, the Tigres score another goal."},
      {"type": "say", "speaker": "Diego", "avatar": "👨", "es": "¡Gol! ¡Dos a dos! ¡Qué partido!", "en": "Goal! Two to two! What a game!"},
      {"type": "q", "prompt": "How does the game end?", "choices": ["The Tigres win", "The Leones win", "It is a tie, two to two"], "answer": 2},
      {"type": "say", "speaker": "Carmen", "avatar": "👩", "es": "Bueno, hoy nadie pierde.", "en": "Well, nobody loses today."},
      {"type": "say", "speaker": "Diego", "avatar": "👨", "es": "¡Los dos equipos ganan y nosotros también! ¿Pizza?", "en": "Both teams win, and so do we! Pizza?"},
      {"type": "say", "speaker": "Carmen", "avatar": "👩", "es": "¡La pizza siempre gana!", "en": "Pizza always wins!"}
    ]
  }
];
